# Generated by Django 2.1.5 on 2019-01-16 09:29

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0003_auto_20181117_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=djstripe.fields.StripeDecimalCurrencyAmountField(decimal_places=2, help_text='Amount to be charged on the interval specified.', max_digits=8, null=True),
        )
    ]
